# Tensorflow2.0 小练习

In [1]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [ ]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数
    （在行的方向上进行归一化）'''
    ##########
    exp_x = tf.exp(x)    
    sum_exp = tf.reduce_sum(exp_x, axis=-1, keepdims=True)
    prob_x = exp_x / sum_exp
    
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [ ]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    exp_x = tf.exp(-x)
    tmp_x = tf.add(exp_x, 1)
    prob_x = tf.divide(1, tmp_x)
    
    # return 1.0 / (1.0 + tf.exp(-x))
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [19]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    log_prob = tf.math.log(x)
    loss = -tf.reduce_sum(label * log_prob, axis=-1)  # 对最后一维求和
    return tf.reduce_mean(loss)  # 返回平均损失
    
    # return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)

print("test_data: ", test_data.shape)
print("prob: ", prob.shape)
print("label: ", label.shape)

label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

test_data:  (10, 5)
prob:  (10, 5)
label:  (10, 5)


np.True_

## 实现 sigmoid 交叉熵loss函数

In [ ]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    loss = -tf.reduce_mean(tf.math.log(x)*label+tf.math.log(1-x)*(1-label))
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
print(prob)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


tf.Tensor(
[0.24474355 0.1844284  0.2303551  0.4909813  0.31234145 0.55157395
 0.51912371 0.82988679 0.41844641 0.48312826], shape=(10,), dtype=float64)
[0. 1. 1. 1. 0. 0. 1. 1. 0. 1.]


np.True_